version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.4.0-browsers

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: update-npm # donwload the lastest version of npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache: # restore the dependency cache
          name: Restore node_modules cache
          key: dependency-cache-{{ checksum "package.json" }}

      - run: # download dependencies
          name: install-node-modules
          command: |
            npm install
            cd dummy_app
            npm install

      - save_cache: # save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
      - run:
          name: Start Server
          command: npm start
          background: true
      
      - run:
          name: Run Tests
          command: npm test


workflows:
  test:
    jobs:
      - build